### PR TITLE
Support for prom-client v13

### PR DESCRIPTION
**Pull request by yorch**
* Support for `prom-client` v13 as it includes breaking changes (https://github.com/siimon/prom-client/releases/tag/v13.0.0)

### CODE REVIEW

**Comment by yorch** [comment]
Fixes #64, #61 and #63

**Comment by yorch** [comment]
@kobik gently reminder :) would be great to merge this, thanks!

**Review by kobik — CHANGES_REQUESTED** [review]
Thanks @yorch!

Can you please add the breaking change to the Changelog file?

**Comment by yorch** [comment]
@kobik sure.. done!

**Comment by kobik** [comment]
> @kobik sure.. done!

thanks @yorch

**Review by kobik — APPROVED** [review]

**Comment by yorch** [comment]
@kobik thanks for the approval, unfortunately I cannot merge this as I don't have privileges.

**Comment by kobik** [comment]
@yorch is like to merge and release both this and custom labels together, that's why I didn't merge it yet

**Comment by yorch** [comment]
@kobik still not sure I follow, eventually you will have to merge one of these first and then the other. Most likely, one of these is gonna cause conflicts with the other that wont bubble up until one of these is merged

**Comment by kobik** [comment]
@yorch , i've made some tests on my end and the current version works with both prom-client 12 and 13, so i think we can bump it by a minor version.

what do you think?

do you see a real reason for bumping a major version?

**Comment by yorch** [comment]
@kobik agree, since there are not actual break changes then if it still works with 12, makes sense to keep the update as a minor version 👍

**Pull request merged**
